apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nextcloud
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_PASSWORD: nextcloudpass
  MYSQL_USER: nextclouduser
  MYSQL_DATABASE: nextclouddb