apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-mysql
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: {{ include "nextcloud.fullname" . }}-mysql