apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-nextcloud
spec:
  type: {{ .Values.service.nextcloud.type }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nextcloud.nodePort }}
  selector:
    app: {{ include "nextcloud.fullname" . }}-nextcloud